### ISSUE TITLE
Survey Form Responsive Issue

### ISSUE THREAD

**Issue by HansikaSachdeva** [ujjwalpuri29/FreeCodeCamp-Projects#1]
When opened using a mobile phone, the background image doesn't cover the whole page. The elements like the text and input fields are not aligned and don't appear on the screen completely.
![24f03082-10f9-44ea-8d35-84c0911f984d](https://user-images.githubusercontent.com/52819652/120523106-2929b300-c3f3-11eb-816d-c701e674881d.jpg)

**Comment by POP1912** [comment]
Can I solve this issue?.

**Comment by chandan-singh02** [comment]
could you give mw permission to solve this problem?

**Comment by ujjwalpuri29** [comment]
@POP1912 @chandan-singh143 I have solved this issue but do let me know if there's any other improvement I can make in the code. Thank you!
